### ISSUE TITLE
请问框架里面，哪些参数适合作为环境变量，而哪些适合被写到配置表里面？

### ISSUE THREAD

**Issue by xiaohuoni** [sorrycc/ama#10]
今天在群里看到一个问题。
> 请问下，如何才能打印 mock 的请求日志呢？

我就在想是设置一个环境变量**MOCK_LOG**
还是设置
```js
mock:{
  log:true
}
```
框架中那么多参数，哪些参数适合作为环境变量，而哪些适合被写到配置表里面？

**Comment by sorrycc** [comment]
日志有通用方案的，mock 是插件，在里面通过 debug 打印日志，然后 `DEBUG=umi-plugin*` 就可以开启插件的日志了。

**Comment by xiaohuoni** [comment]
这个我知道。我的意思是。你那么多参数是怎么规划。配置文件和环境变量

**Comment by sorrycc** [comment]
环境变量通常是临时的，因人而异，不是因项目而异。有些功能点没考虑或者内部业务的整合需求清楚也会放环境变量。

**Comment by xiaohuoni** [comment]
学习了
