### ISSUE TITLE
What does your phone homescreen look like

### ISSUE THREAD

**Issue by ifyour** [sorrycc/ama#12]
:P

**Comment by sorrycc** [comment]
感谢提问，让我把 iPhone 上的应用整理了一遍。

<img src="https://user-images.githubusercontent.com/35128/40951992-1db5fad8-68ac-11e8-94e8-cfc43f3ffc56.PNG" width="322" height="698" />

## 每天用

* **支付宝**
* **微信**
* **Chrome**，代替 Safari，好处是可以和电脑同步
* **Gmail**
* **Reeder**，我是 RSS 重度用户
* **钉钉**，工作交流
* **Shadowrocket**，你懂的，需切换美区安装
* **Twitter**，感觉官方客户端够用了
* **Workflow**，最常用的一个 workflow 是 clipboard to instapaper，用于把微信文章经由 instapaper 保存到 github issue
* **网易云音乐**
* **QQ**

## 资讯

* **知乎**
* **即刻**
* **财新**，有人送了免费的 1 年会员才下的
* **得到**
* **极客时间**
* **知识星球**

## 电商 & 银行

* **手机淘宝**
* **京东**
* **微店**，买过 vpn 之类被淘宝禁用的商品
* **网易严选**
* **闲鱼**
* **美团外卖**
* **招商银行**
* **杭州银行**
* **手机营业厅**，联通

## 游戏

* **王者荣耀**，现在玩地少了
* **绝地求生：刺激战场**，很少玩

## 工具

* **Telegram**
* **Bear**，记录一些临时的想法，优点是漂亮，以及可以和 mac 同步
* **阿里小号**
* **欧路词典**，翻译工具，和 mac 上保持一致
* **Wifi 万能钥匙**
* **1Password**
* **百度网盘**，买会员之后速度还是很快的
* **小猿口算**，利器，10 秒内检查完儿子口算
* **Keep**
* **WaterMinder**
* **115**
* **讯飞语记**
* **Cam Remote**，和 FUJIFILM 相机连
* **GitHawk**，github 客户端
* **交管12123**
* **腾讯手机管家**，拦截骚扰电话和短信

## 交通

我的 1~2 公里出行选择顺序：骑电 -> 摩拜 -> 哈罗 -> ofo

* **哈罗单车**
* **ofo**
* **曹操专车**
* **百度地图**，国内用这个
* **Google Maps**，国外用这个

## 娱乐类

* **Netflix**
* **抖音短视频**
* **微视**
* **Plex**
