### ISSUE TITLE
成哥看框架或者库的源码多吗？多的话是如何去看，看源码能学到什么？希望讲解下

### ISSUE THREAD

**Issue by ghost** [sorrycc/ama#16]

**Comment by ifyour** [comment]
> 如何去看

一起讨论一下, 最近我学习到的一个方法

1. 拿到一个开源项目, 先从 release 入手, check out 到最初的版本
2. 找到能看得懂的版本后, 开始阅读, 其实本质上是从最核心的代码开始读
3. 逐步向后面的版本阅读, 可以用 git 的 diff 工具, 对比每次变更, 以及官方的更新说明
4. 然后有了一定量的输入后, 尝试自己造轮子, 这一步完成后才能代表知识是你的了

期待 @sorrycc 的回答, 应该还有更好的方法, 😄

**Comment by huanghui1** [comment]
@ifyour 不错的方法，不过就是觉得这样学一个框架太久了，有的框架会在release里放上功能对应的PR。

我的方法是不管怎样先跑一遍再说，把它的核心流程了解了，再去了解它的核心架构（感觉在框架里学习到许多架构知识），然后就是把他的功能了解了，看看他是如何实现功能的，最后才是看它的每一个release实现的功能~

**Comment by dkvirus** [comment]
我从 github 上把 umi 源码拉了下来，也 learn bootstrap 安装了依赖包，谁知道怎么进行断点调试。就是很好奇 @sorrycc  在开发的时候是怎么做到调试的。

**Comment by sorrycc** [comment]
@ifyour 👍

我补充几点，以 [reduxjs/redux](https://github.com/reduxjs/redux) 为例。

1. 看源码之前可以先看[官网文档](https://redux.js.org/)，先要会用，再去弄懂 why 。用的过程中把有疑问的点记下来，带着问题去看源码会更有目的性
2. 看源码我通常会对照着用例来看，这样能搞懂各种用法以及边界条件，用例看完通常才会知道源码里的每个分支为什么那么处理，比如 [applyMiddleware.js](https://github.com/reduxjs/redux/blob/master/src/applyMiddleware.js) 和 [applyMiddleware.spec.js](https://github.com/reduxjs/redux/blob/master/test/applyMiddleware.spec.js)
3. 出于个人兴趣的原因，我还会看 package.json。1) 看 [scripts 部分](https://github.com/reduxjs/redux/blob/master/package.json#L37-L50)，可以了解一个库是如何组织的，比如文档实现，用例怎么写和用什么跑，eslint 和 prettier 怎么配合使用，打包逻辑，example 的组织等 2) 看 [dependencies 和 devDependencies 部分](https://github.com/reduxjs/redux/blob/master/package.json#L51-L86)，看看有没有什么依赖库是我不知道的，记下来，下次自己也可以用

**Comment by xiaohuoni** [comment]
我看一个项目都是先按第三步看package.json开始的，看到工具，不知道的，直接先npmjs.org搜索一下，然后找到github地址。发现直接从github上容易找到别的东西。
