### ISSUE TITLE
如何跳出一直写业务逻辑的现状，非科班出生如何系统化的学习从而变得更强

### ISSUE THREAD

**Issue by aLIEzsss4** [sorrycc/ama#2]

**Comment by sorrycc** [comment]
## 如何跳出一直写业务逻辑的现状

昨天我们开会时也有聊到这个话题，做业务的同学觉得一直写业务提高缓慢，晋升机会少这是个普遍的问题。

就我个人而言，我在阿里 10 年多，估计有一半时间是在做业务，比如淘宝首页、购物车、宝贝详情、下单、店铺、全站的页头页尾、支付宝收银台等等。这么长的时间，如果写业务的时候只管实现需求，那就没啥意思了。

举一些我的例子。

维护淘宝首页的时候，印象中搞过这些：

* 性能优化（那会比较流行），然后总结《淘宝首页性能优化心得》
* 做各种统计，除了浏览器、系统占比这些，有意思的很多，比如看看有多少
* 做各种监控，脚本出错监控、首屏广告加载出错
* ...

维护宝贝详情页的时候，

* 性能优化，然后总结《淘宝宝贝详情性能优化心得》
* 详情图片懒加载，节约 cdn 带宽
* jpg 格式切 webp 格式（chrome 支持的格式，比较小），节约 cdn 带宽
* ...

维护购物车页面的时候，

* 不断地重构代码，应用响应式数据的方式
* 写了一个在任何页面都可以把商品添加到购物车的脚本，帮助业务提升，这是我那会升 P 级一个重要的点
* 做出错统计，能实现统计用户在页面上操作到哪一步导致的出错
* 做全站预加载，比如用户是详情 -> 购物车 -> 下单这样的步骤，然后就在上一页预加载下一页的文件，然后观察数据
* ...

等等。

有些具体的事在现在已经过时了，不过前端整体能做的差不多就是：

* 各种数据监控（数据是基础，不然怎么说服别人？）
* 性能优化，思路可以不仅限于前端
* 勤总结，常分享
* 时不时跳出业务想想有啥可以帮助业务提升的点，怎么让用户访问更快，体验更好
* 跟进技术更新，把学到技术应用到业务中，你的业务就是很好的试验田
* 尝试在空闲时间做做技术产品
* 提炼 DPL、技术框架，让自己或同事在做同类产品时能快速完成
* 在阿里的话，还可以写专利赚赚外快，业务上的创新点绝对比框架上多

供参考。

然而，自己去找事做是得看机会和业务的，有些业务很难有动手机会，比如支付宝收银台，我在做这个业务的时候就是束手束脚，一天有一半的时间是花在流程上，完全发挥不出自己的想法。

所以，如果团队 leader 有看到这一点，调整下团队的配比，让团队成员能一边做业务一边做技术产品就再好不过了，可以让团队成员保持活力和激情。比如我们有同学一边写业务一边维护前端框架，有同学一边写业务一边做可视化建站，等等。

## 非科班出生如何系统化的学习从而变得更强

这是个很大的命题，等有时间再来详细写写。我觉得最重要的是不止于会用，得了解原理。经常用的东西了解下背后运行的机制，看的多了，慢慢就融会贯通了，面试时这也是一个重要的考察点。

比如 JavaScript 每天都在用的，我之前就有花比较多的时间把 ECMAScript 规范看了一遍，然后碰到任何语法问题，都能从语法实现上都找到解释，语言层就不是问题了。

**Comment by aLIEzsss4** [comment]
很开心你能很认真的回复 :)

**Comment by sorrycc** [comment]
Updated.

**Comment by OnedayLiu** [comment]
如果当前业务确实没什么可以动手的点呢？
