### ISSUE TITLE
前端如何成长为优秀的框架作者或架构师呢？

### ISSUE THREAD

**Issue by Lxxyx** [sorrycc/ama#4]
## 问题具体描述

想对框架、架构等知识有更深的了解，希望可以开发出像 dva 这种优秀的框架。但因为日常所做的都是普通的业务开发，该如何对这部分知识有更多的了解呢？

## 期望目标
希望在完成日常业务之余，能对框架，架构能有更多的学习和了解，成长为优秀的框架作者或架构师。

**Comment by sorrycc** [comment]
先说下我的经历吧。

在做 dva 之前，我对于前端框架也了解不深，也是处于使用的状态。记得做 dva 之前是在做 [spm](https://github.com/spmjs/spm) 工具，再之前是做支付宝收银台业务，这些和前端框架一点关系都没有。

然后就写了 dva，dva 是源于业务的，并解决了业务开发中使用 redux 不便的痛点的。然后运气比较好，这个痛点也是社区使用 redux 的痛点，所以获得了比较多的认可，以及公司内外大量的用户。有用户就有反馈，有问题需要解决，而我很多的前端框架经验就是在这个过程中逐渐积累的。

另外，dva/umi 靠自己想肯定是想不出来的，得在社区中相关学习借鉴。所以出于发展的需要，我会关注各个前端框架的发展（目前主要是 vue、react，angular 还没有涉猎），但也不仅限于前端框架的部分，详见[我的前端早报](https://github.com/sorrycc/zaobao/issues)。摄入的信息量多了，在需要用的时候就会联想到。

所以，我的建议是：

* **先了解你所用的框架**，知其所以然，之后你会发现每个框架解决的事情都差不多，只是方式不同
* **利用自己是业务开发的优势，了解框架使用有啥痛点**，深入思考后，提 issue 或者线下和人讨论
* **关注开源库的 issue，了解别人遇到的问题**，扩大知识面，一个人能遇到的问题毕竟有限
* **适当地自己造个轮子**，造轮子是个很好的学习过程，说不定造着造着就火了呢？

然后你会发现前端框架也就那么回事，没什么难的。
