### ISSUE TITLE
想知道成哥是如何学习前端的？是看一些库的源码？还是看书或者怎样？你是如何搞懂前端一些底层问题的

### ISSUE THREAD

**Issue by ghost** [sorrycc/ama#6]

**Comment by sorrycc** [comment]
以下是我之前整理但未公开发布的信息流，供参考。

---

<img src='https://shipusercontent.com/281f67595b18247789149818c4931071/Pasted%20Image%202.png' title='Pasted Image 2.png' width=957>

见上图。

Reeder 3、Instapaper 和 Github issue 是三个重要的信息处理环节，Reeder 3 用于阅读 RSS 订阅，处理大量输入，Instapaper 是一个中间环节，用于精读，以及接收不能走 RSS 的输入，Github issue 用于归档。

## Reeder 3

我在 Mac 和 iOS 下都安装了 Reeder 3，保持同步。这是我最主要的信息源，能订阅的直接订阅，不能订阅的想办法（比如 [feed43](https://feed43.com/)，[rss.lilydjwg.me](https://rss.lilydjwg.me/) 等）转成 RSS 再订阅。

RSS 包含：

* 大量国内国外的 Blog
* 一些知乎专栏
* Github Release（比如 webpack、babel、react、redux 等库的 release）
* Github Private Feed
* Youtube 专栏
* Twitter 前端 List 和 Front-End Programming 里 star 超过 50 的信息 (TODO)
* 微信公众号 (TODO)
* ...

## Instapaper

RSS 通常是一扫而过，有些需要深阅读的或者 read it later 的会一键添加到 Instapaper。另外，微信、浏览器访问时看到的文章也会添加到 Instapaper。至于为啥用 Instapaper？主要是添加文章方便，渠道很全，基本上不用担心在某些场景下不能添加的问题。

注意：

* iOS 下安装 Instapaper 需要切到美区账号，没在中国区上架？
* 微信到 Instapaper 需借助 Workflow，可参考知乎的[这篇回答](https://www.zhihu.com/question/23448653/answer/151331421)

然后，Instapaper 其实是个中转站，除了手机上，我很少会在他上面看文章，而是通过他归档到 [sorrycc/reading](https://github.com/sorrycc/reading)。

如何归档？(Instapaper -> Github issue)

具体可以看 [Serverless 实战：打造个人阅读追踪系统](https://blog.jimmylv.info/2017-06-30-serverless-in-action-build-personal-reading-statistics-system/)，主要是通过 ifttt，如果有 Instapaper 有新的 item，在 github 上创建一个 issue。至于在 Instapaper 里存档后自动关闭 github 上的 issue，我也做了，但实际下来感觉用处并不大。

为啥要归档？

* 存在 github 上比较放心
* github issue 可以添加笔记、tag、archive 等
* github issue 可通过 Ship 管理

## Github issues

除了 [sorrycc/reading](https://github.com/sorrycc/reading/issues) 之外，其他的比如周报、计划、笔记、信息收集等也都是在这里（github 私库）处理。

选择在哪做归档处理是很纠结的。。我的选择也是经历了很多次的变更，从最早的 Evernote，到 Quiver，再到 Bear，最后换成 Github issue 。目前，我的所有信息（除了公司内部数据的部分）都会通过 Github issue 来归档，不能公开的放私库。而最近入手的 [Ship](https://www.realartists.com/index.html) 应用，让我更加坚定了通过 Github issue 来归总归档的决心。

![Pasted Image 2.png](https://shipusercontent.com/e7c0d1d48e5fe5be9dd4ddfffaa00eb8/Pasted%20Image%202.png)

Ship 实在是太好用，以至于我都想把 github star 和 twitter star 转成 github issue，然后用它来管理了。

## 参考

* [Serverless 实战：打造个人阅读追踪系统](https://blog.jimmylv.info/2017-06-30-serverless-in-action-build-personal-reading-statistics-system/)
* https://tinyletter.com/sorrycc/letters/message

**Comment by sinchang** [comment]
能分享下 rss 吗？

**Comment by ghost** [comment]
@sorrycc 谢谢回复很详细，还有就是现在流行的前端库，成哥有阅读源码吗，有的话是如何阅读的，自己现在一看就晕了，而且也不知道看能学到什么？

**Comment by xiaohuoni** [comment]
https://github.com/sorrycc/reading not found
