### ISSUE TITLE
umi 编译模块打包

### ISSUE THREAD

**Issue by Jeephe** [sorrycc/ama#7]
请问如何将公共模块独立打包出来，如何配置CommonsChunkPlugin ，比如引入crypto、g2等模块时，文件尺寸会变得比较大，如何通过配置来让umi build出独立的文件。谢谢！

**Comment by sorrycc** [comment]
crypto、g2 等通过 externals 的方式引入呢？

**Comment by sorrycc** [comment]
umi 的问题还是移步 https://github.com/umijs/umi/issues 吧。

**Comment by Jeephe** [comment]
好的，谢谢你的提示，很管用
