### ISSUE TITLE
如何才能成为一个团队里面不可或缺的重要人才

### ISSUE THREAD

**Issue by wangyazhen** [sorrycc/ama#9]
目前是开发前端，并且是只涉及到前端开发，但是想怎么才能成为一个团队里面独当一面的人呢，
可以包括（后端，个人综合，软实力）等方面。

期望：成为大牛

**Comment by sorrycc** [comment]
观察了下我周边的前端高 P 同学，有偏管理的，也有偏技术的，而偏技术的同学基本上都有自己深入的点，比如可视化（antv）、UI 库（antd）、全栈（egg）、前端框架、智能建站、支付宝 IDE（electron）等等。

所以，看你的职业规划吧，如果是偏技术，我觉得应该有计划地让自己成为 T 型人才，有广度，也要有深度。其中深入更重要一些。以我为例，我目前专精的点是前端框架，包括数据流、前端工具、性能优化等，除此之外会涉猎，但不会花时间深究，毕竟精力有限。

> 是要做个全站，想自己带团队做个小公司。 

对于全栈和带团队我没啥经验，给不了你建议。

> 现在感觉是到了瓶颈期

印象中我好像也有过瓶颈期，维护淘宝首页几年之后就没啥想法了，找不到特别想做的事情。瓶颈期主要是得找到突破口吧，比如说换个岗位；或者看看社区发展，适当造个轮子；找不到轮子，就熟悉下目前在用的技术栈，深入参与到某个开源项目里（比如 antd、dva 等），我们有好一些同事就是从开源社区中找到的。
